# Generated by Django 5.2.7 on 2025-10-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(null=True),
        ),
    ]
